server:
  port: 0

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/authService_credenciais
    driver-class-name: org.postgresql.Driver
    password: authService_password
    username: admin

  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      #      defaultZone: http://eureka-server:8761/eureka
      defaultZone: http://localhost:8761/eureka
