spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
            defaultZone: http://eureka-server:8761/eureka
#      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true

