version: '3.8'

services:

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network


  gateway:
    image: streetaparrel-gateway
    build: ./gateway
    container_name: gateway
    depends_on:
      eureka-server:
        condition: service_started
    env_file:
      - .env
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${SERVICEURL_EUREKA}
    ports:
      - "8080:8080"
    networks:
      - microservices-network


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - microservices-network

#  db_product-service:
#    image: mysql:8
#    container_name: db_product-service
#    environment:
#      MYSQL_ROOT_PASSWORD: root_password
#      MYSQL_DATABASE: produto_db
#      MYSQL_USER: produto_user
#      MYSQL_PASSWORD: produto_password
#    ports:
#      - "3307:3306"  # Mapeamento da porta do MySQL para a porta 3307 no host
#    networks:
#      - microservices-network  # Rede personalizada para comunicação


  db_user-service:
    image: mysql:8
    container_name: db_user-service
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"  # Porta exclusiva para o banco do serviço de usuário
    networks:
      - microservices-network  # Mesma rede personalizada

  db_auth-service:
    image: postgres:15
    container_name: db_auth-service
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - microservices-network


networks:
  microservices-network:
    driver: bridge  # Rede customizada para comunicação entre contêineres
