server:
  port: 0

spring:
  application:
    name: servico-usuario
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
  datasource:
    url: jdbc:mysql://localhost:3308/usuario_db
    username: usuario_user
    password: usuario_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

api:
  security:
    token:
      secret: ${JWT_SECRET:12345678}