server:
  port: 8080 # Porta na qual o gateway será executado

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE  # Nome registrado do serviço no Eureka
          predicates:
            - Path=/user/**  # Roteia para esse serviço com prefixo "/user"
          filters:
            - StripPrefix=1
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
#          filters:
#            - StripPrefix=1


eureka:
  client:
    service-url:
#       defaultZone: http://eureka-server:8761/eureka/
       defaultZone: http://localhost:8761/eureka/