server:
  port: 8080 # Porta na qual o gateway será executado

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE  # Nome registrado do serviço no Eureka
          predicates:
            - Path=/user/**  # Roteia para esse serviço com prefixo "/user"

eureka:
  client:
    service-url:
       defaultZone: http://eureka-server:8761/eureka/